Business_Servicing/urls.py
from django.conf.urls import handler400
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Shop.urls', namespace='Shop')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from . import views

app_name = 'Shop'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('HttpResponse_link/', views.HttpResponse_funcion, name='HttpResponse_name'),
]

basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

Shop/models.py
from unicodedata import decimal
from django.db import models
from django.conf import settings
from django.db.models.fields import URLField
from django.urls import reverse

class ProductsManager(models.Manager):
    def get_queryset(self):
        return super(ProductsManager, self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('Shop:category_list', args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='product_creator', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    old_price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductsManager()

    description_title = models.CharField(max_length=255, null=True)

    title1 = models.CharField(max_length=255, null=True)
    img1 = models.ImageField(upload_to='images/', null=True)
    description1 = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('Shop:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

class Baner(models.Model):
    img_baner = models.ImageField(upload_to='images/', null=True)
    titel_baner = models.CharField(max_length=255)
    description_baner = models.TextField(blank=True)
    link = models.URLField(max_length=225, null=True)

    def __str__(self):
        return self.titel_baner

class BottomFolder(models.Model):
    description_folder = models.TextField(blank=True)

    product1 = models.CharField(max_length=255)
    product_Link1 = models.URLField(max_length=225, null=True)
    product2 = models.CharField(max_length=255)
    product_Link2 = models.URLField(max_length=225, null=True)
    product3 = models.CharField(max_length=255)
    product_Link3 = models.URLField(max_length=225, null=True)
    product4 = models.CharField(max_length=255)
    product_Link4 = models.URLField(max_length=225, null=True)

    useful_links1 = models.CharField(max_length=255)
    useful_links_link1 = models.URLField(max_length=255, null=True)
    useful_links2 = models.CharField(max_length=255)
    seful_links_link2 = models.URLField(max_length=255, null=True)
    useful_links3 = models.CharField(max_length=255)
    seful_links_link3 = models.URLField(max_length=255, null=True)
    useful_links4 = models.CharField(max_length=255)
    seful_links_link4 = models.URLField(max_length=255, null=True)

    contact1 = models.CharField(max_length=255)
    contact_link1 = models.URLField(max_length=225, null=True)
    contact2 = models.CharField(max_length=255)
    contact_link2 = models.URLField(max_length=225, null=True)
    contact3 = models.CharField(max_length=255)
    contact_link3 = models.URLField(max_length=225, null=True)
    contact4 = models.CharField(max_length=255)
    contact_link4 = models.URLField(max_length=225, null=True)

    instagram = models.URLField(max_length=255, null=True)
    reddit = models.URLField(max_length=255)
    facebook = models.URLField(max_length=255)
    email = models.URLField(max_length=255)


    def __str__(self):
        return self.description_folder

Shop/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from .models import Category, Product, BottomFolder, Baner


# Create your views here.

def categories(request):
    return {
        'categories': Category.objects.all()
    }

def all_products(request):
    products = Product.products.all() # query: storing all od the data inside this veriable
    bottomFolder = BottomFolder.objects.all()
    baner = get_object_or_404(Baner)
    return render(request, 'Shop/home.html', {'products': products, 'bottomFolder': bottomFolder, 'baner': baner})
    
def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    bottomFolder = BottomFolder.objects.all()
    return render(request, 'Shop/products/detail.html', {'product': product, 'bottomFolder': bottomFolder})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.products.filter(category=category)
    bottomFolder = BottomFolder.objects.all()
    return render(request, 'Shop/products/category.html', {'category': category, 'products': products, 'bottomFolder': bottomFolder})

def HttpResponse_funcion(request):
    return HttpResponse('<h1>HttpResponse import test...</h1>')

templates/Shop/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}

{% if category %}
    {{ category.name }}
{% else %} 
    Products
{% endif %}

{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{ category.name|title }}</div>

      {% if not products %}
          <div class="col-12">There are currently no services activate.</div>
          <div class="col-12">go back to main page click <a href="{% url 'Shop:all_products' %}">here</a>, sorry for the lak of services, will be up shortly.</div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
      {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">9min read</small>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
      {% endif %}
      
    </div>
  </div>
</main>

{% endblock %}

templates/Shop/products/detail.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock %}


{% block content %}

<body style="background-color: #F8F9FA;">

<!--------------------------------------teoba product page----------------------------------------->
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                            
                            </div>
                            <div class="col-6 text-end"><button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Add to basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>
<!----------------x----------------------teoba product page------------------------x----------------->

    
<!-----------------------------------------------------------------------INFORMATION--------------------------------------------------------------------------->
<div class="container-sm">
    <nav class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Descripción</a>
        <a class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Comentarios</a>
        <a class="nav-link disabled" id="nav-disabled-tab" data-bs-toggle="tab" href="#nav-disabled" role="tab" aria-controls="nav-disabled" tabindex="-1" aria-disabled="true">Disabled</a>
    </nav>

    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            <h1>{{ product.description_title }}</h1>

            <h3>{{ product.title1 }}</h3>
            <img style="width: 100%; height: 123px;" src="{{ product.img1.url }}" alt="">
            <p>{{ product.description1 }}</p>
        
            <h3>{{ product.title2 }}</h3>
            <img style="width: 100%; height: 123px;" src="{{ product.img2.url }}" alt="">
            <p>{{ product.description2 }}</p>
        
            <h3>{{ product.title3 }}</h3>
            <img style="width: 100%; height: 123px;" src="{{ product.img3.url }}" alt="">
            <p>{{ product.description3 }}</p>
        </div>

        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">Sebastian is testing</div>
        
        <div class="tab-pane fade" id="nav-disabled" role="tabpanel" aria-labelledby="nav-disabled-tab">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laudantium minima repellat incidunt facilis obcaecati blanditiis corrupti ad officia doloribus ullam sapiente ipsum, nemo a, excepturi voluptatem voluptatibus velit eum dignissimos ut, nam tempora? Reiciendis illo itaque veritatis eligendi fuga, mollitia ratione totam veniam esse in.</div>
    </div>
    </div>
<!---------------------------------------X------------------------------------ INFORMATION---------------------------------------X--------------------------------------->
</body>

<script>
    $(document).on('click', '#add-button', function (e) {       // function the someone clicked the button add-button
        e.preventDefault();
        $.ajax({                                                // ajax requets, send & return data to server
            type: 'POST',                                       // what type of request is it
            url: '{% url "basket:basket_add" %}',               // send data to basket:basket_add
            data: {                                             // dta that gets send
                productid: $('#add-button').val(),              // grab the value       
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",          // send csrf token
                action: 'post'
            },
            success: function (json) {                          // responce if success
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}               // responce if error
        });
    })
</script>

{% endblock %}