Business_Servicing/urls.py
from django.conf.urls import handler400
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Shop.urls', namespace='Shop')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from . import views

app_name = 'Shop'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('HttpResponse_link/', views.HttpResponse_funcion, name='HttpResponse_name'),
]

basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

basket/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse

from Shop.models import Product, BottomFolder
from .basket import Basket

# Create your views here.

def basket_summary(request):
    basket = Basket(request)
    bottomFolder = BottomFolder.objects.all()
    return render(request, 'basket/summary.html', {'basket': basket, 'bottomFolder': bottomFolder})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        ##product_qty = int(request.POST.get('productqty'))
        try:
            product = Product.objects.get(id=product_id) 
        except:
            raise Http404                                
        ##basket.add(product=product, qty=product_qty)
        basket.add(product=product, qty=1)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

'''
def basket_summary(request):
    basket = Basket(request)
    return render(request, 'Shop/basket/summary.html', {'basket': basket})

def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':             ## ckeck if ajax sent a post request
        product_id = int(request.POST.get('productid'))  ## what the product_id that's in ajax
        ##product = get_object_or_404(Product, id=product_id)

        try:
            product = Product.objects.get(id=product_id) ## gets data from database
        except:
            raise Http404                                 ## if any error's show
                                     
        basket.add(product=product)                      ## saving the data to the session
        response = JsonResponse({'test':'data'})         ## retuening th edata
        return response

'''

templates/basket/summary.html
{% extends "../Shop/base.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}
    
<main class="pt-5">
    <div class="container">
      {% if basket|length == 0 %}
        <div class="col-12">you basket in empty <a href="{% url 'Shop:all_products' %}">Home</a></div>
      {% else %}
      <h1 class="h5">Shopping basket</h1>
        {% for item in basket %}
          {% with product=item.product %}
          <div data-index="{{product.id}}" class="row mb-4 border product-item">
            <div class="col-md-3 col-lg-2 order-md-first bg-light">
              <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
              <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
                <h1 class="h5 pt-2">{{ product.title }}</h1>
              </a>
              <div class="border">
                <div class="col border-bottom">
                  <div class="row p-3">
                    <div class="col-6">Hardback Book</div>
                    <div class="col-6 text-end"><span class="h6 fw-bold"><small>MX </small> ${{ product.price }}</span></div>
                  </div>
                </div>
                <div class="col">
                  <div class="row p-3">
                    <div class="col-12">
                      <button type="button" id="delete-button" data-index="{{product.id}}"
                        class="btn btn-outline-secondary btn-sm delete-button">
                        Delete
                      </button>
                      <a role="button" href="{% url 'payment:basket' %}" class="btn btn-success fw-bold" type="button">Checkout</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endwith %}
        {% endfor %}
      {% endif %}
      <div class="col-12 text-end">
        <div class="h6 fw-bold">Sub Total: MX<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div></div>
      </div>
    </div>
  </main>

  <script>
    // Delete Item
    $(document).on('click', '.delete-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_delete" %}',
        data: {
          productid: $(this).data('index'),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          $('.product-item[data-index="' + prodid + '"]').remove();
          document.getElementById("subtotal").innerHTML = json.subtotal;
          document.getElementById("basket-qty").innerHTML = json.qty
        },
        error: function (xhr, errmsg, err) {}
      });
    })
  
    // Update Item
    $(document).on('click', '.update-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_update" %}',
        data: {
          productid: $(this).data('index'),
          productqty: $('#select' + prodid + ' option:selected').text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          document.getElementById("basket-qty").innerHTML = json.qty
          document.getElementById("subtotal").innerHTML = json.subtotal
        },
        error: function (xhr, errmsg, err) {}
      });
    })
  </script>
{% endblock %}